---
name: Pull request pre-check build & test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v3.0.0

  build-fedora-container-on-ubuntu:
    runs-on: ubuntu-latest
    needs: [pre-commit]
    env:
      REGISTRY: quay.io
      # github.repository as <account>/<repo>
      IMAGE_TAG: ${{ github.event.number || github.ref_name  }}  # use PR number else ref_name -> branch name
    permissions:
      contents: read
      packages: write

    steps:
      - name: Print IMAGE_TAG to be used
        run: echo "${{ env.IMAGE_TAG }}"

      - name: Set lower case image name derived from repository name
        run: |
          echo "IMAGE_NAME=${IMAGE,,}" >> ${GITHUB_ENV}
        env:
          IMAGE: '${{ github.repository }}'

      - name: Get source
        uses: actions/checkout@v3

      # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
      - name: Log into ghcr.io registry
        if: github.event_name == 'pull_request'
        run: |
          echo "REGISTRY=ghcr.io" >> ${GITHUB_ENV}
          export CR_PAT=${{ secrets.GHCR_TOKEN }} && echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # https://github.com/docker/login-action
      - name: Log into quay.io registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME}}
          password: ${{ secrets.REGISTRY_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile.test
          context: .
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          labels: ${{ steps.meta.outputs.labels }}

  run-docker-compose-on-ubuntu:
    runs-on: ubuntu-latest
    needs: [build-fedora-container-on-ubuntu]
    env:
      REGISTRY: quay.io
      # github.repository as <account>/<repo>
      IMAGE_NAME: ${{ github.repository }}
      IMAGE_TAG: ${{ github.event.number || github.ref_name  }}  # use PR number else ref_name -> branch name

    permissions:
      contents: read
      packages: read

    steps:
      - name: Print IMAGE_TAG to be used
        run: echo "${{ env.IMAGE_TAG }}"

      - name: Set lower case image name derived from repository name
        run: |
          echo "IMAGE_NAME=${IMAGE,,}" >> ${GITHUB_ENV}
        env:
          IMAGE: '${{ github.repository }}'

      # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
      - name: Log into ghcr.io registry
        if: github.event_name == 'pull_request'
        run: |
          echo "REGISTRY=ghcr.io" >> ${GITHUB_ENV}
          export CR_PAT=${{ secrets.GHCR_TOKEN }} && echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # https://github.com/docker/login-action
      - name: Log into quay.io registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME}}
          password: ${{ secrets.REGISTRY_TOKEN }}


      - name: Pull the image and try to run it
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker images
          docker-compose --help
